
development:
  adapter: postgresql
  encoding: unicode
  database: magnetic_poetry_development
  pool: 5
  host: localhost
  username: Froese
  password:
  


test:
  adapter: postgresql
  encoding: unicode
  database: magnetic_poetry_test
  pool: 5
  host: localhost
  username: Froese
  password:
  

production:
  adapter: postgresql
  encoding: unicode
  database: magnetic_poetry_production
  pool: 5
  host: localhost
  username: Froese
  password:
