require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StoryPartsController do

  # This should return the minimal set of attributes required to create a valid
  # StoryPart. As you add validations to StoryPart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "x" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StoryPartsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all story_parts as @story_parts" do
      story_part = StoryPart.create! valid_attributes
      get :index, {}, valid_session
      assigns(:story_parts).should eq([story_part])
    end
  end

  describe "GET show" do
    it "assigns the requested story_part as @story_part" do
      story_part = StoryPart.create! valid_attributes
      get :show, {:id => story_part.to_param}, valid_session
      assigns(:story_part).should eq(story_part)
    end
  end

  describe "GET new" do
    it "assigns a new story_part as @story_part" do
      get :new, {}, valid_session
      assigns(:story_part).should be_a_new(StoryPart)
    end
  end

  describe "GET edit" do
    it "assigns the requested story_part as @story_part" do
      story_part = StoryPart.create! valid_attributes
      get :edit, {:id => story_part.to_param}, valid_session
      assigns(:story_part).should eq(story_part)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StoryPart" do
        expect {
          post :create, {:story_part => valid_attributes}, valid_session
        }.to change(StoryPart, :count).by(1)
      end

      it "assigns a newly created story_part as story_part" do
        post :create, {:story_part => valid_attributes}, valid_session
        
      end

      it "renders JSON" do
        # 
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved story_part as @story_part" do
        # Trigger the behavior that occurs when invalid params are submitted
        StoryPart.any_instance.stub(:save).and_return(false)
        post :create, {:story_part => { "x" => "invalid value" }}, valid_session
        assigns(:story_part).should be_a_new(StoryPart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StoryPart.any_instance.stub(:save).and_return(false)
        post :create, {:story_part => { "x" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested story_part" do
        story_part = StoryPart.create! valid_attributes
        # Assuming there are no other story_parts in the database, this
        # specifies that the StoryPart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StoryPart.any_instance.should_receive(:update).with({ "x" => "1" })
        put :update, {:id => story_part.to_param, :story_part => { "x" => "1" }}, valid_session
      end

      it "assigns the requested story_part as @story_part" do
        story_part = StoryPart.create! valid_attributes
        put :update, {:id => story_part.to_param, :story_part => valid_attributes}, valid_session
        assigns(:story_part).should eq(story_part)
      end

      it "redirects to the story_part" do
        story_part = StoryPart.create! valid_attributes
        put :update, {:id => story_part.to_param, :story_part => valid_attributes}, valid_session
        response.should redirect_to(story_part)
      end
    end

    describe "with invalid params" do
      it "assigns the story_part as @story_part" do
        story_part = StoryPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StoryPart.any_instance.stub(:save).and_return(false)
        put :update, {:id => story_part.to_param, :story_part => { "x" => "invalid value" }}, valid_session
        assigns(:story_part).should eq(story_part)
      end

      it "re-renders the 'edit' template" do
        story_part = StoryPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StoryPart.any_instance.stub(:save).and_return(false)
        put :update, {:id => story_part.to_param, :story_part => { "x" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested story_part" do
      story_part = StoryPart.create! valid_attributes
      expect {
        delete :destroy, {:id => story_part.to_param}, valid_session
      }.to change(StoryPart, :count).by(-1)
    end

    it "redirects to the story_parts list" do
      story_part = StoryPart.create! valid_attributes
      delete :destroy, {:id => story_part.to_param}, valid_session
      response.should redirect_to(story_parts_url)
    end
  end

end
